### ISSUE TITLE
Explicit time zone for Hack09?

### ISSUE THREAD

**Issue by tjd2002** [NeurodataWithoutBorders/nwb_hackathons#114]
The [agenda ](https://github.com/NeurodataWithoutBorders/nwb_hackathons/edit/master/HCK09_2020_Remote/README.md) reads:
"The workshop schedule is centered around 9am-6pm Central European Time."

Does this refer to CET (UTC+1) or CEST (UTC+2)? CEST is Central European Summer Time, and will be in effect in EU countries at the time of the meeting.

Either way, I think it would be best to list the UTC offset for the sake of being explicit.

(Hoping to drop in and see some of you all online in a few weeks!)

**Comment by rly** [comment]
CEST (UTC+2). Fixed now. Thanks @tjd2002 !
