### ISSUE TITLE
Build Pull Requests Action

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb_hackathons#205]
@CodyCBakerPhD would you be able to help create a GitHub Action to this repo that builds PRs so we can examine them before merging?

**Comment by CodyCBakerPhD** [comment]
What exactly would that entail? Just testing validity of external links?

**Comment by bendichter** [comment]
No, rendering the website

**Comment by bendichter** [comment]
It's a jekyll site. It might be more trouble than it's worth, I don't know.

**Comment by CodyCBakerPhD** [comment]
I show it using GitHub Pages as of 2 weeks ago: https://github.com/NeurodataWithoutBorders/nwb_hackathons/deployments/activity_log?environment=github-pages

These already seem to b using the actions: https://github.com/NeurodataWithoutBorders/nwb_hackathons/actions

If you want it to display/be required on a PR I can try to add it to the branch protections (but would require admin permissions for this repo)

**Comment by bendichter** [comment]
Yes, it would be great to have a button to view the build in the PR. I have now given you admin privileges

**Comment by CodyCBakerPhD** [comment]
Well, it's technically added and working..

It is definitely quite slow, but after looking at why there really isn't much to do about it

It seems a part of the design of GitHub pages is that they 'deploy' (to some URL) the build from Jekyll (which only takes 1-2 minutes) by uploading it to the GitHub repository as an 'upload artifact', which is a painfully slow process with no way to speed it up

So the ~10 minute waiting time between commits is entirely just waiting for the artifact to be uploaded

**Comment by oruebel** [comment]
Thanks @CodyCBakerPhD
