### ISSUE TITLE
site not updated

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb_hackathons#207]
I don't see the latest update on the website and it has been 15 hrs. @CodyCBakerPhD is it possible that this might have something to do with the changes you made to enable site preview?

**Comment by bendichter** [comment]
oh, it's rendering from the gh-pages branch, isn't i

**Comment by CodyCBakerPhD** [comment]
@bendichter That will break the preview

**Comment by CodyCBakerPhD** [comment]
The main page should also be able to pull from the `gh-pages` branch too (that's the usual default for pages anyway)

**Comment by bendichter** [comment]
@CodyCBakerPhD `gh-pages` is the default for the pattern where gh-pages just holds the website of the library and the other branches are for developing a library. It's not applicable here since the entire repository is the website, so `main` is more appropriate. Changing the pages branch to gh-pages in this case broke the deployment of the actual up-to-date site. Is there a way to get previews working without breaking the site update workflow?

**Comment by CodyCBakerPhD** [comment]
> Is there a way to get previews working without breaking the site update workflow?

The preview requires the site be rendered on a non-main branch

**Comment by CodyCBakerPhD** [comment]
I can probably make an action to keep the `gh-pages` branch up to date any time something is merged to `main`

**Comment by bendichter** [comment]
hm, maybe that would be best. That way we wouldn't get the automated commits on the main branch and would only have our own commits

**Comment by CodyCBakerPhD** [comment]
OK it should work now - you can test this for sure by

1) merging #210 and wait 1-2 minutes

2) go to that page on the the `gh-pages` branch 

3) confirm that extra bit of text is there

Then I'll open a follow-up PR to remove the text from the page on main

Merging that follow up PR will also remove it from `gh-pages`

You can then tell GitHub Pages deployment to deploy from `gh-pages`

Now the main site stays up to date with changes to main, and you can preview proposed changes on PRs

**Comment by CodyCBakerPhD** [comment]
@bendichter Mind if I swap the GitHub Pages back to deploying from `gh-pages` now to see if it allows previews?

**Comment by CodyCBakerPhD** [comment]
Looks good now, minus the ability to easily navigate links on preview deployments

Good to close?

**Comment by bendichter** [comment]
yes. Thankyou for all the help!
