### ISSUE TITLE
Add NWB GUIDE instructions for conversion workshop

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb_hackathons#275]
Since GUIDE will likely be a main tool for the conversion workshop it will be useful to add links to installation instructions for GUIDE on the website (once ready) here: 

https://github.com/NeurodataWithoutBorders/nwb_hackathons/blob/4ecf1b6f3927089664160915e7f88d71801151e6/HCK19_2024_Remote/README.md?plain=1#L34-L45

**Comment by CodyCBakerPhD** [comment]
That will be easy, they can always be found here: https://nwb-guide.readthedocs.io/en/latest/installation.html

Just let me know when website is ready

**Comment by oruebel** [comment]
The PR for the website has already been merged, so good to go make this change
