### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/nwb_hackathons#4]
The UA number should be added to `_config.yml` as 

```
# Google Analytics
google_analytics: UA—XXXXXXXX-X
```

See https://desiredpersona.com/google-analytics-jekyll/

**Comment by rly** [comment]
Completed in https://github.com/NeurodataWithoutBorders/nwb_hackathons/commit/c793d797ec3211256f5bb7dfefd9c102bba43518
