### ISSUE TITLE
Remaining Tasks for HCK04

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/nwb_hackathons#6]
* Required to finalize invitation email
  * [ ] Review and update [registration form](https://docs.google.com/forms/d/160JFIJ8lJreBs1bDdNcXHiGETKyn5gXErGC5WWF7saU/edit)
  * [ ] Define time and medium for [preparatory meetings](https://github.com/NeurodataWithoutBorders/nwb_hackathons/tree/master/HCK04_2018_Seattle#preparatory-videoconferences) (e.g hangout ? zoom ? ...)
  * [ ] Update [Who to Contact](https://github.com/NeurodataWithoutBorders/nwb_hackathons/blob/master/README.md#who-to-contact)
  * [ ] Update [Logistics information](https://github.com/NeurodataWithoutBorders/nwb_hackathons/blob/master/HCK04_2018_Seattle/README.md#logistics)
  * [ ] Finalize and send [invitation email](https://docs.google.com/document/d/1ovDja0J8vNnSfVqh1GogCLDGXKBny0PRC6t3dHY3VyM/edit)

* Breakout Session
   * [ ] Add one document per session and assign presenter/organizer/owner
   * [ ] Schedule [Breakout Sessions](https://neurodatawithoutborders.github.io/nwb_hackathons/HCK04_2018_Seattle/#breakout-sessions) and [update calendar](https://neurodatawithoutborders.github.io/nwb_hackathons/HCK04_2018_Seattle/Calendar/README.html)

* Other tasks
  * [x] Finalize layout of [HCK04 welcome page](https://neurodatawithoutborders.github.io/nwb_hackathons/HCK04_2018_Seattle) - Assigned to @jcfr
  * [x] Add project template.  See [here](https://neurodatawithoutborders.github.io/nwb_hackathons/HCK04_2018_Seattle/Projects/) - Assigned to @jcfr
  * [x] Move [suggested project](https://github.com/NeurodataWithoutBorders/nwb_hackathons/tree/master/HCK04_2018_Seattle#projects-how-to-add-a-new-project) originally added by @nicain and @neuromusic from website to forum - Assigned to @jcfr
  * [x] Add one or two concrete [project](https://github.com/NeurodataWithoutBorders/nwb_hackathons/tree/master/HCK04_2018_Seattle#projects-how-to-add-a-new-project) - Assigned to @jcfr and @mgrauer 
  * [ ] Update [Local Organizing Commitee](https://github.com/NeurodataWithoutBorders/nwb_hackathons/blob/master/HCK04_2018_Seattle/README.md#local-organizing-committee) details
  * [ ] Setup Google Analytics for the hackathon website. See #4
  * [ ] Prepare attendees satisfaction survey
  * [ ] Add a code of conduct. See [here](https://discourse.itk.org/t/developing-the-itk-code-of-conduct/608) for guidance
  * [x] Add `ORGANIZER-FAQ.md` to answer common questions - Assigned to @jcfr - See [here](https://github.com/NeurodataWithoutBorders/nwb_hackathons/blob/master/ORGANIZER-FAQ.md)

**Comment by lydiang** [comment]
Re: registration form

Is the link above the one I should use in the invite email? Is there a step to make it publicly available?

**Comment by jcfr** [comment]
> Is the link above the one I should use in the invite email?

This link will work great:
https://docs.google.com/forms/d/e/1FAIpQLSfBJXXxNkAaiBcPJJRV67v2R1aFu2L5ZOPzXkt_edSi5UAoVA/viewform

>  Is there a step to make it publicly available?

Yes. It was initially restricted to used of the "kitware.com" organization, this has now been fixed. Opening an "incognito" tab and copying the link is expected to work.

**Comment by tjd2002** [comment]
Closing as we’re at hack06 now :)
